NethermindEth/warp

warp/yul/BuiltinHandler.py, warp/yul/ToCairoVisitor.py, warp/yul/main.py
Also added local reference copying for mapping_.. functions and removed __warp_block's that were only reverting.
=> wrap external function calls for memory_dict access

warp/if-flattening.cairo, warp/if-flattening.sol, warp/yul/ScopeFlattener.py, warp/yul/ToCairoVisitor.py
Flatten if-blocks such that they are abstracted away to functions with only one if statement
=> Implement if flattening to address if-blocks that may have mutation

tests/yul/ERC20.cairo, tests/yul/ERC20_storage.cairo, tests/yul/for-loop-with-break.cairo, tests/yul/for-loop-with-continue.cairo, tests/yul/if-flattening.cairo, warp/yul/ToCairoVisitor.py
The default dict needs to be finalised before the end of the program, as explained here: https://www.notion.so/nethermind/bb52b38dd5244093a07d4a4fefda1c1a?v=9b578f69d11149c9a65c5cfbd06b6b61&p=e2317bbb3ace41b585d9eb89d645c553
The call to `default_dict_finalize` reliably revokes all references so I've had to store all implicits in local.
=> Finalize the default dict

.github/workflows/build.yml, Makefile, pyproject.toml, requirements.txt, setup.py, warp/cli/compilation/Compile.py, warp/cli/compilation/Contract.py, warp/cli/compilation/opcode_tables.py, warp/cli/compilation/utils.py, warp/transpiler/Operation.py, warp/transpiler/Operations/Code.py, warp/transpiler/Operations/Gas.py, warp/transpiler/Operations/Invalid.py, warp/transpiler/Operations/NoOp.py, warp/transpiler/Operations/PC.py, warp/transpiler/Operations/Ternary.py, warp/transpiler/Operations/Unary.py, warp/yul/FunctionPruner.py, warp/yul/utils.py
To reformat everything locally run `black .` from the root directory
of the project.
=> run black formatter check in CI instead of in a precommit hook

.github/workflows/build.yml, Makefile, tests/cli/tests.bats
For now, we just test that all command finish with exit code 0
=> add cli tests

.github/workflows/build.yml
Still, we need to test kudu on other platforms, so we still test transpilation where we can
=> run CI on macos, since github macos runners are more performant

scripts/yul/compile_sol_files_in_tests_yul.sh
Add script to compile tests/yul/*.sol
Ignore .warp-deps
=> Compile script and update .gitignore

README.md, warp/cli/warp_cli.py, warp/yul/main.py
Optimizes the import statements to improve the CLI response time from 0.9 seconds to 0.05 seconds.
=> Improve autocompletion feature for CLI

warp/cairo-src/evm/calls.cairo, warp/yul/BuiltinHandler.py, warp/yul/ToCairoVisitor.py
Adds all the remaining Yul builtiins. Throws an error if certain builtins are present in the generated Yul.
=> add remaining builtins

requirements.txt, setup.py
there is already a version with that number on pypi but with different
code
=> bump the sol-warp version

tests/behaviour/view-function_test.py
it's basically the same as pure-function and we already benchmark it
=> remove benchmarking view-function

README.md, poetry.lock, pyproject.toml, src/warp/cli/cli.py, src/warp/cli/commands.py
- Added network as a required argument
- Used `starknet tx_status` command for the query
- Added missing sections to the Table of Contents in the `readme` file
=> Fix CLI status query

README.md
We support msg.data and msg.sig (handled in yul via calldata)
=> Update unsupported features

tests/behaviour/copy_byte_array_to_storage.sol, tests/behaviour/copy_byte_array_to_storage_test.py, tests/behaviour/delete_storage_array.sol, tests/behaviour/delete_storage_array_test.py, tests/behaviour/dirty_storage_bytes_long.sol, tests/behaviour/dirty_storage_bytes_long_test.py, tests/behaviour/dirty_storage_dynamic_array.sol, tests/behaviour/dirty_storage_dynamic_array_test.py, tests/behaviour/dirty_storage_struct.sol, tests/behaviour/dirty_storage_struct_test.py, tests/behaviour/slot_access.sol, tests/behaviour/slot_access_test.py
Add semanticTests substituting keccak256 with the pedersen built-in using inline assembly.
=> Add semanticTests with pedersen

src/transpiler.ts, src/utils/cliOptionParsing.ts
Adds a small helper function that guarantees all our passes have unique and well formatted keys
=> Assert pass order has valid keys

.github/workflows/build.yml, .gitignore, package.json, starknet-testnet/generateMarkdown.py, starknet-testnet/server.py, starknet-testnet/util.py
Implement benchmarking for a dashboard
=> Implement benchmarking

starknet-testnet/server.py
Small bugfix for IndexError when running server.py without arguments
=> Fix no args server crash

tests/behaviour/contracts/external_function_inputs/static_array_return_index.sol, tests/behaviour/expectations/behaviour.ts
Adding tests for static array tests.
Have a look at the test function names. What do you think of this convention. I found the names for tests were getting longer and longer as they got more complex. The description in `expectations/behaviour.ts` gives the details about the test rather than the name of the function?
=> Adding tests

tests/behaviour/contracts/conversions/widthsignWideningItoUchange.sol, tests/behaviour/contracts/conversions/widthsignnarrowingItoUchange.sol, tests/behaviour/contracts/conversions/widthsignnarrowingUtoIchange.sol, tests/behaviour/contracts/conversions/widthsignwideningUtoIchange.sol, tests/behaviour/expectations/behaviour.ts
This reverts commit 94551f314be9a4ba3e80b69e44f23d111f6db147.
=> Revert accidental warp-ts commit

src/passes/generateGetters/gettersGenerator.ts, tests/behaviour/contracts/public_state/state_vars.sol, tests/behaviour/expectations/behaviour.ts
This PR will fix the typestring bug for the public state getter functions.
=> Getter_typestring

example_contracts/imports/importContract.sol, example_contracts/imports/importInterface.sol, example_contracts/imports/importStruct.sol, example_contracts/imports/importfrom.sol, src/testing.ts, src/utils/getTypeString.ts
Added support for specific import of Interface
Added test for specific import of Library 
Contd PR #307
=> Specific import for interface

src/passes/literalExpressionEvaluator/literalExpressionEvaluator.ts, src/passes/literalExpressionEvaluator/rationalLiteral.ts, src/warplib/implementations/maths/shl.ts, src/warplib/implementations/maths/shr.ts, tests/behaviour/contracts/maths/shl.sol, tests/behaviour/contracts/maths/shr.sol, tests/behaviour/expectations/behaviour.ts, tests/behaviour/expectations/semantic_whitelist.ts
All shift bugs are fixed. Relevant test cases are added.
=> Shift bugs fix

src/index.ts, src/starknetCli.ts
Adds an option to allow stand alone compiling of a cairo file
=> Add cli compile options

example_contracts/this_methods_call.sol, src/cairoWriter.ts, src/passes/builtinHandler/thisKeyword.ts, src/passes/publicFunctionSplitter/internalFunctionCallCollector.ts, src/testing.ts, src/utils/utils.ts, tests/behaviour/contracts/cross_contract_calls/this_methods_call.sol, tests/behaviour/expectations/behaviour.ts
Support `this.method_name(..args)`
=> `this` methods calls

.github/workflows/build.yml, starknet-testnet/generateMarkdown.py
Separates the `build` and `benchmark` as two jobs
=> Benchmark: Separate build and benchmark

src/cairoUtilFuncGen/memory/arrayConcat.ts, src/passes/bytesConverter.ts, tests/behaviour/contracts/concat/bytes.sol, tests/behaviour/expectations/behaviour.ts, warplib/dynamic_arrays_util.cairo, warplib/maths/bytes_access.cairo
In solidity you can concatenate bytesX as well
=> Concat fixed bytes

src/cairoWriter.ts, src/passes/implicitConversionToExplicit.ts
Handles variable declaration statements with gaps on the lhs
=> Var decl gaps

src/cairoUtilFuncGen/storage/dynArrayPushWithArg.ts, src/passes/references/arrayFunctions.ts, tests/behaviour/contracts/storage/dynamic_arrays.sol, tests/behaviour/expectations/behaviour.ts
Fixes push taking calldata dynamic arrays and dereferences the result of push when it is a dynamic array
=> Push fixes

src/cairoUtilFuncGen/storage/copyToStorage.ts
Add scaling for fixed bytes on storage to storage copy (e. g. bytes2[] -> bytes4[]). The following semantic tests pass now:
* array_copy_different_packing
* array_copy_storage_storage_static_simple
* array_copy_target_leftover
* array_copy_target_leftover2
* array_copy_target_simple
* array_copy_target_simple2
=> Add fixed bytes storage to storage scaling

src/cairoUtilFuncGen/storage/storageDelete.ts
fixes: `tests/behaviour/solidity/test/libsolidity/semanticTests/structs/delete_struct.sol`
=> fix WSMAP_DELETE redefinition

src/passes/references/expectedLocationAnalyser.ts
fixes: `tests/behaviour/solidity/test/libsolidity/semanticTests/structs/copy_from_storage.sol`
`tests/behaviour/solidity/test/libsolidity/semanticTests/structs/struct_constructor_nested.sol`
=> Fix expected location of memory assignments

src/passes/inheritanceInliner/constructorInheritance.ts
Addresses tests/behaviour/solidity/test/libsolidity/semanticTests/types/struct_mapping_abstract_constructor_param.sol
=> Add lookup node for constructor inheritance

.github/workflows/build.yml
Skips the benchmark step in CI for pull requests.
=> CI: Skip benchmark for pull requests

src/utils/cloning.ts
Fixes https://github.com/NethermindEth/warp/issues/575
=> Fix documentation cloning bug

readme.md, src/passes/rejectUnsupportedFeatures.ts
Fixes https://github.com/NethermindEth/warp/issues/574
Fixes https://github.com/NethermindEth/warp/issues/576
Fixes https://github.com/NethermindEth/warp/issues/577
Fixes https://github.com/NethermindEth/warp/issues/578
=> Make clear features that are not supported

src/index.ts
Naive way to compile any number of sol files. Handy for transpiling whole projects.
=> Transpile multiple files

v3-core/contracts/libraries/FullMath.sol, v3-core/contracts/libraries/TickMath.sol, v3-core/contracts/libraries/UnsafeMath.sol
=> Replace assembly with corresponding sol snippet

src/passes/namedArgsRemover.ts, src/passes/usingForResolver.ts
https://www.notion.so/nethermind/AUDIT-CVF-52-usingForResolver-ts-8514d7aa93bd45c58cb2841f6d43a14a
https://www.notion.so/nethermind/AUDIT-CVF-8-namedArgsRemover-ts-a6e8e0c5e6854017b5a0c9ba9e12008c
=> follow suggestions: CVF 8, 52

example_contracts/unsupportedFunctions/gasleft.sol, src/passes/rejectUnsupportedFeatures.ts, src/testing.ts
=> gasleft is an unsupported feature

readme.md
=> Add instructions for installing gmp and exporting CFLAGS for arm mac

example_contracts/contracts_as_input.sol, src/cairoUtilFuncGen/inputArgCheck/inputCheck.ts, src/testing.ts, src/utils/nodeTypeProcessing.ts
When checking input args, treat contracts as addresses
=> Implicit checks minor fix

src/passes/literalExpressionEvaluator/literalExpressionEvaluator.ts
Tickets:
https://www.notion.so/nethermind/AUDIT-CVF-19-literalExpressionEvaluator-ts-f02224ca8fbe47bbb68229c9f627d6dd
https://www.notion.so/nethermind/AUDIT-CVF-18-literalExpressionEvaluator-ts-ed82a56b05ef4405b3c8d5124191f91c
https://www.notion.so/nethermind/AUDIT-CVF-22-literalExpressionEvaluator-ts-a4ff9fe5e2ed44ea9360a6b0adc963c5
https://www.notion.so/nethermind/AUDIT-CVF-21-literalExpressionEvaluator-ts-8c007e7d952f479aa84d79bf7c587520
https://www.notion.so/nethermind/AUDIT-CVF-20-literalExpressionEvaluator-ts-9cdb4ef0be504fe1ad4c4f537f8906f5
=> Audit advices for literal expr eval

src/utils/cloning.ts
Not elegant but gets the job done
=> Hotfix for clone bug

src/utils/cloning.ts
=> Fix documentation clone

package.json, src/passes/cairoStubProcessor.ts, src/passes/identifierManglerPass/declarationNameMangler.ts, src/passes/inheritanceInliner/functionInheritance.ts, src/passes/inheritanceInliner/inheritanceInliner.ts, src/utils/astPrinter.ts, src/utils/nodeTypeProcessing.ts, yarn.lock
[yes] behaviour tests pass locally
=> Fix function overriding

.github/workflows/semantic.yml, src/autoRunSemanticTests.ts
Earlier, the semantic CI was passing for all instances becuase it was not detecting failing CI tests. Resulting in false positives. This PR fixes that behaviour.
=> Semantic CI false positives fix

src/utils/defaultValueNodes.ts
Errors on src/utils/defaultValueNodes.ts are not only about delete operator
Ticket:
https://www.notion.so/nethermind/Delete-operator-error-messages-9df964c092bb4e2a83558b494daa1d19
=> fix error messages in defaultValueNodes

.husky/pre-commit, package.json, yarn.lock
=> Run eslint on staged files pre commit
