NethermindEth/warp

- src/EvmToCairo.py
- src/Operations/Binary.py
- src/Operations/Memory.py
- src/Operations/Ternary.py
- src/Operations/Unary.py
the method guarantees to return a new unique name every time it's
called (on the same object)
Removes the need to remember to increase `n_locals` by one each time.
> add `request_fresh_name` method for state

- warp/cli/compilation/utils.py
- warp/transpiler/Operations/Arithmetics.py
The `Exp` class was using the `pow` operator to do the evaluation, but this could be very inefficient if the numbers are too large. Using Binary Exponentiation algorithm fixes that problem.
> Binary Exponentiation method for Exp Operation

- examples/ERC20/ERC20.sol
- warp/yul/ToCairoVisitor.py
- warp/yul/main.py
Currently, it is not possible for external Cairo functions to take or return Uint256 arguments. So here I have had to change the way external functions are defined and called.
> Convert external function args and return values to arg_low arg_high

- examples/ERC20/ERC20.sol
- warp/ERC20.cairo
- warp/for-loop-with-break.cairo
- warp/for-loop-with-break.sol
- warp/for-loop-with-continue.cairo
- warp/for-loop-with-continue.sol
- warp/yul/BuiltinHandler.py
- warp/yul/ExpressionSplitter.py
- warp/yul/ForLoopEliminator.py
- warp/yul/LeaveNormalizer.py
- warp/yul/ScopeFlattener.py
- warp/yul/ToCairoVisitor.py
- warp/yul/main.py
- warp/yul/parse.py
- warp/yul/utils.py
- warp/yul/yul_ast.py
After this transformation there are no for-loops, breaks or continues in a Yul AST. In all places, that would require a `return` in Cairo, Yul `leave`'s are placed
> replace breaks with leaves

- warp/cairo-src/evm/calls.cairo
- warp/yul/BuiltinHandler.py
Before this change generated cairo code for solidity contracts which used `msg.sender`, looked like this:
```
let (local a: Uint256) = caller()
```
After the changes:
```
from evm.calls import get_caller_address_uint256
let (local a: Uint256) = get_caller_address_uint256()
```
> Replace yul caller() with get_caller_data_uint265()

- examples/ERC20/ERC20.cairo
- warp/for-loop-with-break.cairo
- warp/for-loop-with-continue.cairo
- warp/if-flattening.cairo
- warp/yul/BuiltinHandler.py
- warp/yul/ToCairoVisitor.py
The algorithm relies on several assumptions. The first one is that
before each function call all implicit arguments are stored as
'local's.
The second one is that each builtin function defines a set of implicit
arguments that it uses. Due to the nature of how cairo rebinds
implicit arguments, these get rebound as non-local, revokable
references. So, we need to make a local copy of them. Complex
functions defined in the cairo file gather their set of implicit
arguments from functions that are used in them. The yul contract
is supposed to be topologically sorted, so it should be generally
fine. In the case of mutually recursive functions a set of
required implicit arguments can't be gathered before the function
call. So we simply assign to such functions all possible implicit
arguments.
> copy only implicits necessary to copy

- requirements.txt
- tests/yul/ERC20.cairo
- tests/yul/ERC20_storage.cairo
- tests/yul/for-loop-with-break.cairo
- tests/yul/for-loop-with-continue.cairo
- tests/yul/if-flattening.cairo
- warp/yul/FunctionPruner.py
- warp/yul/ScopeFlattener.py
- warp/yul/ToCairoVisitor.py
- warp/yul/main.py
- warp/yul/utils.py
- Create `FunctionPruner` class to remove unused functions.
- Modify `ScopeFlattener` class to obtain a single reverting block, instead of creating a new one every time an if branch was reverting
> Remove unused functions

- .github/workflows/build.yml
- tests/yul/ERC20.cairo
- tests/yul/ERC20_storage.cairo
- tests/yul/calldatacopy.cairo
- tests/yul/for-loop-with-break.cairo
- tests/yul/for-loop-with-continue.cairo
- tests/yul/if-flattening.cairo
- tests/yul/return-var-capturing.cairo
- warp/yul/ToCairoVisitor.py
With the new cairo-lang release (0.4.2), structs are supported as return variables for external functions.
This PR removes the splitting of return variable in external functions.
> Remove splitting of variable returns in external functions

- warp/yul/main.py
gen-yul-json-ast now lives at: https://github.com/NethermindEth/kudu
This PR should be merged after https://github.com/NethermindEth/kudu/pull/21 is merged
> Change binary name gen-yul-json-ast -> kudu

- warp/cli/warp_cli.py
Similar to #86, 
This PR adds help strings and command descriptions to all the CLI commands for warp.
> CLI: Add documentation for all commands

- .github/workflows/develop-ci.yml
- .github/workflows/main-ci.yml
Building solc on github self-hosted macos runners is a problem.
We make PRs to main only for "releases". CI for main tests for all the
possible platforms: macos 10.15, macos 11, ubuntu etc. All the
executables needed for CI (solc, kudu) are built by team members
that own macs.
We make PRs to develop as we regularly do them in the normal process
of development. CI only runs for ubuntu. Executables for macos
are not updated.
> add separate CI configurations for develop and main

- requirements.txt
- tests/ast/ifs-to-flatten-scope.ast.result
- tests/ast/revert-condition.ast.result
- tests/yul/ERC20.cairo
- tests/yul/ERC20_storage.cairo
- tests/yul/c2c.cairo
- tests/yul/calldatacopy.cairo
- tests/yul/calldataload.cairo
- tests/yul/calldatasize.cairo
- tests/yul/constructors_dyn.cairo
- tests/yul/constructors_nonDyn.cairo
- tests/yul/for-loop-with-break.cairo
- tests/yul/for-loop-with-continue.cairo
- tests/yul/for-loop-with-nested-return.cairo
- tests/yul/function-with-nested-return.cairo
- tests/yul/if-flattening.cairo
- tests/yul/payable-function.cairo
- tests/yul/pure-function.cairo
- tests/yul/return-var-capturing.cairo
- tests/yul/returndatasize.cairo
- tests/yul/short_string.cairo
- tests/yul/simple-storage-var.cairo
- tests/yul/sstore-sload.cairo
- tests/yul/view-function.cairo
- warp/yul/NameGenerator.py
- warp/yul/ScopeFlattener.py
"reverting" ifs are if-expressions where at least one branch results
in the revert.
Problem: we extract all "reverting" ifs into one function –
__warp_cond_revert. It's not correct, sometimes reverting ifs
have different code.
Solution: disable extracting reverting ifs. It's okay to do. Since at
least one branch is a revert, references are not ambiguous at the
end of the if-expression.
> disable extracting "reverting" ifs

- Makefile
- tests/yul/ERC20.cairo
- tests/yul/ERC20_storage.cairo
- tests/yul/arrays.cairo
- tests/yul/arrays.sol
- tests/yul/c2c.cairo
- tests/yul/calldataload.cairo
- tests/yul/calldatasize.cairo
- tests/yul/constructors_dyn.cairo
- tests/yul/constructors_nonDyn.cairo
- tests/yul/if-flattening.cairo
- tests/yul/pure-function.cairo
- tests/yul/returndatasize.cairo
- tests/yul/short_string.cairo
- tests/yul/simple-storage-var.cairo
- tests/yul/sstore-sload.cairo
- tests/yul/view-function.cairo
- warp/cairo-src/evm/array.cairo
- warp/cairo-src/evm/hashing.cairo
- warp/cairo-src/evm/output.cairo
- warp/yul/BuiltinHandler.py
Problem: before we tried to map solidity storage variables to cairo
storage variables. The approach was somewhat limited. Solidity
storage mappings and arrays can be curried. Cairo ones – can't.
We had to heavily modify solidity compiler and still didn't
support all the possible storage variables, e.g. structs.
Solution: with Shahar's suggestion we decided on the following. We
just substitute keccak hash for storage access with a pedersen
hash, native to cairo. It results in very slight modifications to
solidity, as we only had to add another builtin instruction. It
does lead to the bigger size of the generated code.
> update executables to ones that use pedersen for storage acccess

- tests/ast/add-leaves.ast.result
- tests/ast/cairo-keywords-for-names.ast.result
- tests/ast/expression-splitter.ast.result
- tests/ast/functions-to-prune.ast.result
- tests/ast/ifs-to-flatten-scope.ast.result
- tests/ast/multiple-for-loops.ast.result
- tests/ast/nested-for-loops.ast.result
- tests/ast/revert-condition.ast.result
- tests/ast/switch.ast.result
- tests/ast/switch_test.py
- tests/ast/utils.py
- warp/yul/AstTools.py
- The new printer for ast generates yul code, except for the `if` statements. Yul language does not support `else` branches, however our visitors generate them, therefore the printer outputs them. Also, type Uint256 is omitted from type annotations, since it is the default one.
- The `AstPrinter` was removed and test cases results were fixed according to the new format
> Implement a printer for the ast that returns a yul-like code

- requirements.txt
> add upper limit on the numpy version

- tests/behaviour/delegatecall-attack.sol
- tests/behaviour/delegatecall-attack_test.py
- tests/golden/c2c.cairo
- tests/golden/delegatecall.cairo
- tests/golden/delegatecall.sol
- warp/cairo-src/evm/array.cairo
- warp/cairo-src/evm/calls.cairo
- warp/cairo-src/evm/yul_api.cairo
- warp/yul/BuiltinHandler.py
The implementation abstracts from the concrete (usual or delegate)
call function. It takes the call function as a parameter. This is
unnecessary and will have to be reverted if/when functions for
delegate and usual calls will differ in signature. The
generalization was done as a fun exercise in low-level Cairo.
Adding a more complex test is complicated by some bugs in the way
constructors are generated.
> support for delegatecall

- tests/golden/ERC20.cairo
- tests/golden/ERC20_storage.cairo
- warp/yul/RevertNormalizer.py
- warp/yul/ToCairoVisitor.py
- warp/yul/storage_access.py
We decided to move away from creating separate storage vars based on
function names. It's fragile and unreliable. However, some code
for it was still left in warp, it's time to clean it up.
> remove old code for extracting storage var getters

- tests/golden/ERC20.cairo
- tests/golden/ERC20_storage.cairo
- tests/golden/arrays.cairo
- tests/golden/constructors_dyn.cairo
- tests/golden/constructors_nonDyn.cairo
- tests/golden/ctor-check.cairo
- tests/golden/delegatecall.cairo
- tests/golden/if-flattening.cairo
- tests/golden/simple-storage-var.cairo
- tests/golden/sstore-sload.cairo
- warp/yul/storage_access.py
Before 0.6.2 Cairo couldn't handle struct parameters for storage
variables, so we had to split each Uint256 into its low and high
part. It's no longer necessary.
> remove splitting of parameters in the storage variable

- tests/benchmark/IntegralMath.cairo
- warp/cairo-src/evm/uint256.cairo
- warp/yul/BuiltinHandler.py
The standard library version of this function it uses
`uint256_unsigned_div_rem`, which is quite slow. The new version
primarily uses bitwise operations and a much faster felt
`unsigned_div_rem`.
That shaves ~300 steps from every call.
> optimize uint256 shr

- tests/behaviour/for-loop-no-condition.sol
- tests/behaviour/for-loop-no-condition_test.py
- tests/golden/for-loop-no-condition.cairo
- tests/golden/for-loop-no-condition.sol
- tests/golden/for-loop-with-nested-return.cairo
- warp/yul/ForLoopEliminator.py
- warp/yul/VariableInliner.py
- warp/yul/yul_ast.py
The problem with the previous approach was that when we encounter an
assignment, we simply ignore it if the RHS is a function
call. This is wrong, since the value of the variables on the LHS
has changed. An example: `var a = 5; a = f(); return a` gets
transformed to `return 5`.
The solution is to invalidate variables on assignments from a function
call.
> invalidate variables' values on function calls in VariableInliner

- tests/golden/ctor-check.cairo
- tests/golden/delegatecall.cairo
- warp/cli/warp_cli.py
- warp/yul/main.py
Implements a second parameter in `transpile_from_yul`. This is a string which allows one to change the order of the Optimizing Visitors according to the following map:
```
function_map = {
"v": VariableInliner,
"c": ConstantFolder,
"o": FoldIf,
"l": LeaveNormalizer,
"r": RevertNormalizer,
"f": FunctionPruner,
"d": DeadcodeEliminator,
}
```
I tested these changes against the tests we have defined in our make file. All of these tests pass apart from a few unit tests in 
`python -m pytest scripts/yul/compilation_test.py -v --tb=short --workers=auto`
I'm working on fixing these failues. After that, I'll implement a command line parameter which will take a string of letters which will act as keys according to the above dictionary. Marking this PR as a draft until then.
> Implement pipelining order for optimizing visitors

- tests/benchmark/WETH10.sol
Replaced `msg.value` with a constant value. This is fine in this case since we're just benchmarking the calls and don't care about the exact state.
> Fix weth benchmark

- .gitattributes
Was browsing the repo on GH and thought it might benefit from the `.gitattributes` trend that's been popping up in [other projects](https://github.com/OpenZeppelin/cairo-contracts/blob/main/.gitattributes) to enable basic coloring for cairo code.
Feel free to close if not interested or just wanna wait for official GH support :)
> Enable python-based syntax highlightling for .cairo files

- scripts/isoltest
- src/warp/kudu.py
Turns out that all the different `kudu` and `isoltest` bins for macos work on all the macos platforms so I've eliminated the different version and have grouped them collectively under `darwin`. This simplifies our release process because we just need to build one.
> Remove redundent macos copies

- README.md
- poetry.lock
- pyproject.toml
- scripts/utils/mload.py
- src/warp/yul/BuiltinHandler.py
- src/warp/yul/ConstantFolder.py
- src/warp/yul/FunctionGenerator.py
- src/warp/yul/ToCairoVisitor.py
- src/warp/yul/parse.py
- src/warp/yul/storage_access.py
- tests/behaviour/address_test.py
- tests/behaviour/delegatecall-attack_test.py
- tests/behaviour/immutables.sol
- tests/behaviour/immutables_test.py
- tests/behaviour/malicious-calldata_test.py
This PR adds support for immutables by implementing two new builtins, `SetImmutable` and `LoadImmutable`.
This also adjusts the parsing mechanism a little by changing how strings are handled in case of `setimmutable` and `loadimmutable`. 
This also adds a test for verification of the working of above functions.
> Add support for Immutables: `setimmutable` and `loadimmutable`

- example_contracts/external_function.sol
- src/cairoWriter.ts
- src/testing.ts
- src/utils/cairoTypeSystem.ts
modify cairoWriter such that calls to methods on contracts get changed to the form the cairo expects. E.g. `a.f(arg1)` in solidity becomes `ContractType.f(a, arg1)`
> modify external contract method call

- src/testing.ts
Fixes bug for status `CairoCompileFailed` (`bin/warp test`)
The Actual Outcome will print status for `.sol` and `.cairo` files separately 
Eg:
```
Test: example_contracts/loops/for-loop-with-nested-return
Expected outcome: Success
Actual outcome:
example_contracts/loops/for-loop-with-nested-return.sol : Success
example_contracts/loops/for-loop-with-nested-return__WARP_CONTRACT__WARP.cairo : CairoCompileFailed
```
> Fix Actual Outcome of testing.ts

- package.json
Adds a yarn command to fix any cairo formatting issues in warplib based on the command used by the CI to check for such issues
> Add yarn formatlib to format warplib

- tests/behaviour/expectations/behaviour.ts
Behaviour tests were commented out by mistake in my earlier PR #281. This PR reverts that change.
> Uncomment behaviour tests

- src/passes/rejectUnsupportedFeatures.ts
Issues were encountered with imports of the form `import {A, B} from 'file'`. This should be dealt with in the future, but for now this PR marks such imports as not supported yet
> Reject specific imports

- src/passes/inheritanceInliner.ts
- src/utils/cloning.ts
- tests/behaviour/contracts/inheritance/modifiers/modifierInheritance.sol
- tests/behaviour/contracts/inheritance/modifiers/modifierOverriding.sol
- tests/behaviour/expectations/behaviour.ts
Added functionality to handle modifier inheritance within `inheritanceInliner` pass. It follows the same approach taken by function inheritance.
> Modifier inheritance

- example_contracts/comments.sol
- src/cairoWriter.ts
- src/testing.ts
- src/utils/cloning.ts
Preserves comments of the form `/** */` and `///` by utilizing the `StructuredDocumentation` node that gets added as a child to the node described in the documentation. 
To-Do;
Example:
```
/// Contract Declaration test
contract HelloWorld {
/** Function 
Declaration test
*/
function getConstant() public pure returns (uint256) {
return 5;
}
/** Variable Declaration test */
uint256 x = 5;
}
```
In the above contract, the documentation for `uint256 x = 5` does not get preserved.
> Implement documentation by preserving comments

- requirements.txt
Marshmallow 8.5.4 was released yesterday and causes starknet-compile to crash, this specifies that 8.5.3 should be installed
> Install older marshmallow-dataclass version

- src/cairoWriter.ts
- src/passes/references/dataAccessFunctionaliser.ts
- tests/behaviour/contracts/expressions/ineffectual.sol
Detects struct constructors that are direct children of expression statements and treats them as a `let`, since a struct constructor call is not a valid cairo statement
> Handle ineffectual structs

- src/passes/inheritanceInliner/inheritanceInliner.ts
- src/passes/inheritanceInliner/utils.ts
InheritanceSpecifiers can contain function calls, which causes issues with later passes which can try to extract those calls into statements because there's nowhere for the statements to go. As InheritanceInliner copies these calls into the constructor, they InheritanceSpecifiers can be safely removed once InheritanceInliner has run
> Inheritance removal

- tests/behaviour/behaviour.test.ts
- tests/behaviour/expectations/semantic_whitelist.ts
Semantic test files which contain multiple individual tests were having them run in a random order due to improperly handled async code. This PR fixes it to run them in the correct order. Additionally I've blacklisted a few more tests that are not relevant/will not be supported
> Semantic test fix

- example_contracts/using_for/imports/user_defined.sol
`using Nums for uint256 global` causes a compiler error in the new solc version (0.8.14), but did not in 0.8.13. This removes it from the test it was breaking
> Remove 'global' from using for

- src/passes/index.ts
- src/passes/typeStringsChecker.ts
- src/transpiler.ts
Some `ElementaryTypeName` nodes were noticed to have undefined typestrings in the input AST. This PR adds a new pass that ensures these typestrings are filled in, and then checks the AST to assert that all `TypeName` nodes have a defined typestring.
> Implement TypeStringsChecker pass

- example_contracts/typestrings/enumArrays.sol
- src/passes/enumConverter.ts
- src/testing.ts
This PR updates the EnumConverter pass to handle typestring better. The pass can now also handle Enum arrays, functions with Enum parameters, etc. 
This PR also adds an example contract which covers various cases like Enum arrays or function types.
> Update EnumConverter pass

- example_contracts/userDefinedFunctionCalls.sol
- src/passes/userDefinedTypesConverter.ts
- src/testing.ts
- src/utils/getTypeString.ts
This PR updates the UserDefinedTypesConverter pass to handle typestrings better. Introduces changes that ensure uniformity in how the three type replacement passes update the typestrings for Expressions and VariableDeclarations.
> Update UserDefinedTypesConverter pass

- tests/behaviour/behaviour.test.ts
- tests/util.ts
Adds a limit to the number of parallel processes the tests use in an attempt to stop the CI crashing
> Reduce CI memory usage

- src/cairoUtilFuncGen/storage/mappingIndexAccess.ts
- src/cairoUtilFuncGen/storage/storageDelete.ts
- src/passes/references/storedPointerDereference.ts
- src/passes/rejectUnsupportedFeatures.ts
- src/utils/nodeTypeProcessing.ts
- src/utils/utils.ts
- tests/behaviour/contracts/storage/mappings.sol
- tests/behaviour/expectations/behaviour.ts
Fixing bug where mapping types pointing to reference types could not be used. This was because datalocation 'default' was in the typestring of the MappingIndexAccess function, which is not possible for reference types and therefore was causing an exception.
> Reference Types in Mapping Values

- tests/behaviour/expectations/index.ts
- tests/behaviour/expectations/semantic_exceptions.ts
**The Issue:**
There are some semantic tests with expected failures where out of bound arguments are passed. For example: 65536 for a uint16 type. Unlike behaviour tests, the semantic test suite uses an `AbiCoder` object that transcodes these values into tests. Hence instead of being read as a string, the out of boud values are wrapped around and get changed unintentionally. This causes the X-fails semantic tests to not pass. 
**The Solution:**
This PR implements a solution where these selected semantic tests with out of bounds values are handled differently than the other semantic tests. This fixes the issue because now the arguments are being passed as strings and hence will not get wrapped around. This is implemented in a way that the internal handling is abstracted from the end user. …
> Implement semanticTest exceptions

- tests/behaviour/behaviour.test.ts
- tests/util.ts
The test suite changes to prevent unlimited multithreading also broke the skipping of the compile stage if the transpile stage fails. This fixes it
> Skip test fix

- src/solCompile.ts
The buffer carrying the json representation of the solidity contracts was being maxed out for intermediate sized contracts (for example https://github.com/JorikSchellekens/warp-demo/blob/main/ERC20/presets/ERC20PresetFixedSupply.sol). 
This is a short term fix
> Increase max buffer size for solc json output

- .gitattributes
I originally committed this, but since official support landed, figure I'd come clean up after myself :)
> Remove .gitattributes in favor of official GitHub highlighting

- src/cairoUtilFuncGen/base.ts
- src/passes/references/expectedLocationAnalyser.ts
- tests/behaviour/contracts/copy_storage_to_memory/static_arrays.sol
- tests/behaviour/expectations/behaviour.ts
Fixes a bug where scalar types in inline arrays were given the expected location of the array, not default
> Array element location

- tests/behaviour/expectations/semantic.ts
Fixed length arrays are encoded as tuples, not as ptr,len pairs, so the prepended length is not needed
> Fix fixed length array encoding for semantic tests

- src/passes/loopFunctionaliser/continueToLoopCall.ts
- src/passes/loopFunctionaliser/utils.ts
- src/passes/loopFunctionaliser/whileLoopToFunction.ts
- tests/behaviour/contracts/loops/loops.sol
- tests/behaviour/expectations/behaviour.ts
The following problems were addressed: 
- When creating parameters for functions by cloning, the identifiers referencing those parameters kept the old references instead of changing to the cloned ones, which meant that collecting unbound variables in the body of the new function, for example, would result in identifiers pointing to variables that don't even exist in the scope of this function.
> To solve this, a mapping was created to store <old_variable_id, cloned_variable>, and then with a pass through the children of the node, all identifiers reference declaration were changed to point to their corresponding new variable.
- The wrong parameters were being passed to: the method that creates function calls from `continue`s and the method that creates the function call for the loop. This …
> Loop references issues

- src/passes/bytesConverter.ts
- src/passes/userDefinedTypesConverter.ts
- src/utils/getTypeString.ts
Problem was having with the typestring in the tree of Literal#18 after LiteralExpressionEvaluator is wrong, and after UserDefinedTypesConverter it's even more . So this PR solves this problem.
> solved the issue with typestring in Literal#18 node for too long literal

- src/passes/externImporter.ts
VARIABLE DECLARATION: There is no need for any action for importing variable declarations, whether it is a free constant or a contract's member variable.
When a variable is imported from another file or declared and used from the same file as:
- free: the constant variable is taken into the main contract
- inheritance: the inherited contract's member variable is taken into the main contract
- member access: the called member variable is taken into the main contract
NOTE: Even though member access is taken into the contract, it is taken as C.member(), which does not exist in Cairo, hence it is a bug.
IMPORT DIRECTIVE: There is no need for any action for import directives. A imports B, B imports C -> A uses the variables, functions, and structs of the C with no problem, since the functions …
> Extern import cleaned up

- src/passes/enumConverter.ts
- src/passes/typeInformationCalculator.ts
- tests/behaviour/contracts/enums/singleEnum.sol
- tests/behaviour/contracts/enums/singleEnum7.sol
- tests/behaviour/expectations/behaviour.ts
The old method for replacing enum literals didn't handle nested member accesses properly, such as `ContractName.EnumName.Value`. The new approach starts as soon as it finds a member access and replaces as soon as it can instead of always recursing all the way in
> Fix enum literal replacement

- src/passes/builtinHandler/shortCircuitToConditional.ts
- src/passes/index.ts
- src/passes/tupleFixes/index.ts
- src/passes/tupleFixes/tupleFiller.ts
- src/passes/tupleFixes/tupleFlattener.ts
- src/transpiler.ts
- src/utils/utils.ts
- tests/behaviour/behaviour.test.ts
- tests/behaviour/contracts/expressions/tupleEdgeCases.sol
- tests/behaviour/expectations/behaviour.ts
getNodeType and the TypeNode system as a whole do not handle tuples with empty slots well (getNodeType throws an exception in such cases, and TypeNodes don't have a way of expressing empty tuple slots). As such, this pass runs before any AST checking can and removes or fills empty tuple slots as appropriate, fixing the typestrings. It also flattens single element non-array tuples as they add nothing to the tree, but make processing harder
> TupleFlattener and TupleFiller

- .github/workflows/build.yml
- package.json
- readme.md
- starknet-testnet/generateMarkdown.py
- starknet-testnet/server.py
This PR adds a new field in the benchmark denoting the size of the JSON file given to the testnet. 
This PR also groups the function names by their contract. Earlier, the invoked functions were being written out individually which was not very readable. 
This PR also changes the CI to push benchmarks only when a commit is merged and not on pull requests. This will clear up clutter on the warp-ts-benchmark branch.
> Benchmark: Add JSON file size, and group functions by contract

- starknet-testnet/server.py
Currently, if transaction executor goes out of resources then it raises an exception, but now it'll return to the sender with an appropriate error message.
> return error msg in case of OUT_OF_RESOURCE

- src/cairoWriter.ts
- src/passes/tupleAssignmentSplitter.ts
- tests/behaviour/contracts/calldata/passingDynArrayInternally.sol
- tests/behaviour/contracts/tuples/calldata_tuple.sol
- tests/behaviour/expectations/behaviour.ts
While returning an index of an array `return arr[0];`, both length and value (with a wrong syntax) were returned previously, while it should have been only the value.
> Return index access bug

- src/testing.ts
Excludes the WARP FREE functions from compilations.
Updates the testing.ts expected outcomes.
> Exclude WARP FREE from compilation

- starknet-testnet/generateMarkdown.py
A quite small fix which removes the function_steps being added where it shouldn't be in the markdown file.
> Formatting fix in benchmark markdown

- src/passes/inheritanceInliner/constructorInheritance.ts
- tests/behaviour/contracts/inheritance/constructors/order_of_eval.sol
- tests/behaviour/expectations/behaviour.ts
Constructors are executed from the "most base-like" to the "most derived" according to the order of linearization. However, expressions passed as arguments for those constructors are evaluated first (before the execution of constructors) and this is done in the reverse order of execution, or in other words, from the "most derived" to the "most base-like".
This PR addresses the previous issue, so that the arguments are evaluated in the correct order
> Order of evaluation of arguments in constructors

- src/passes/references/expectedLocationAnalyser.ts
- tests/behaviour/contracts/cross_contract_calls/this_methods_call.sol
- tests/behaviour/expectations/behaviour.ts
Initially contract type state variables has DataLocation as `strorage` which were creating problems when we access the variable, now the DataLocation is `default` and it is working as expected.
> change expected loc of contract state_var

- src/passes/implicitConversionToExplicit.ts
Now `expressions/unary_too_long_literal` semantic test is passing.
> bug fix: too_long_literal typename gen

- src/warplib/implementations/maths/mod.ts
- tests/behaviour/behaviour.test.ts
- tests/behaviour/contracts/maths/remainder.sol
- tests/behaviour/expectations/behaviour.ts
The warplib mod function requires bitwise pointer when dealing with signed values narrower than 256 bits, all other versions only require range_check. This progresses the viaYul/detect_mod_signed test, though it still requires the div/mod by 0 not throwing task to succeed fully
> Fix mod implicits

- src/passes/references/index.ts
- src/passes/storageAllocator.ts
- tests/behaviour/expectations/semantic_whitelist.ts
Now, `tests/behaviour/solidity/test/libsolidity/semanticTests/libraries/using_library_mappings_return.sol` is passing
> make every lib fns private

- src/utils/defaultValueNodes.ts
- src/utils/nodeTypeProcessing.ts
- tests/behaviour/expectations/semantic_whitelist.ts
Previously default values for reference types and mappings went into memory. This switches it so that if the variable is a type that can't go in memory, then it is given a placeholder initialValue that matches its type
> Handle unitialised storage pointers

- src/ast/ast.ts
- src/cairoWriter.ts
- src/passes/implicitConversionToExplicit.ts
- src/utils/utils.ts
- tests/behaviour/contracts/calldata/returningDynArrayExternally.sol
- tests/behaviour/expectations/behaviour.ts
External function calls with return types like `bytes memory` need to be treated as calldata returns. This modifies extractToConstant to check for this case and change the location of the constant
> Split external function calls returning dynarrays properly

- example_contracts/old_code_gen_err.sol
- example_contracts/old_code_gen_err_7.sol
- src/solCompile.ts
- src/testing.ts
The files listed below and a few more fail with the error listed below when we try to compile through YUL, so we can't get the AST for all files through with viaIR enabled.
In this PR we try the standard-json flag with the `viaIR` enabled first and if there are errors we try with `viaIR` disabled.
example_contracts/using_for/library.sol
example_contracts/variable_declarations.sol
example_contracts/view_function.sol
and many more fail with:
YulException: Variable <<x>> is <<n>> slot(s) too deep inside the stack.
> Fix old code generator error

- src/passes/references/index.ts
- src/passes/references/stateVarRefFlattener.ts
- tests/behaviour/contracts/storage/scalars.sol
Flattens `Contract.var` down to just `var`, which is safe since we mangle names and have handled inheritance and getters by this point
> Handle Contract.var even without inheritance

- src/passes/enumConverter.ts
Now `tests/behaviour/solidity/test/libsolidity/semanticTests/libraries/internal_library_function_bound_to_enum.sol` is passing
> Add missing case enum converter pass

- src/cairoUtilFuncGen/storage/mappingIndexAccess.ts
- src/cairoWriter.ts
- src/passes/expressionSplitter/conditionalFunctionaliser.ts
- src/passes/generateGetters/gettersGenerator.ts
- src/passes/implicitConversionToExplicit.ts
- src/passes/literalExpressionEvaluator/literalExpressionEvaluator.ts
- src/passes/literalExpressionEvaluator/rationalLiteral.ts
- src/passes/tupleAssignmentSplitter.ts
- src/passes/typeInformationCalculator.ts
- src/utils/getTypeString.ts
- src/utils/nodeTemplates.ts
- tests/behaviour/contracts/copy_memory_to_storage/dynamic_arrays.sol
- tests/behaviour/contracts/public_state_vars/structs.sol
- tests/behaviour/contracts/storage/swap.sol
- tests/behaviour/expectations/behaviour.ts
- tests/behaviour/expectations/semantic_whitelist.ts
GetNodeType was failing because it was being called on nodes detached from the tree that rely on struct definition nodes to resolve their typing. Conditionals were failing for the same reason so I've bundled the fix in with this. Additionally, this addresses the string default issue, and an issue with bytes and strings passed into our generated functions being dereferenced when they should not be
> Fix tuple assignment for structs

- src/passes/rejectUnsupportedFeatures.ts
- tests/behaviour/expectations/semantic_whitelist.ts
Throw `WillNotSupportError` in `tests/behaviour/solidity/test/libsolidity/semanticTests/libraries/library_stray_values.sol`
> throw unsupported error: Free fns in exp stmt

- src/passes/abiExtractor.ts
Solc-typed-ast's canonical signature extraction methods fail on arrays with non-literal typenames. GetNodeType succeeds as long as the typestring is valid though, so this PR first uses getNodeType to calculate the length if necessary and inserts it as a literal
> Non literal array length

- src/cairoUtilFuncGen/memory/memoryRead.ts
- src/passes/references/expectedLocationAnalyser.ts
- src/passes/tupleAssignmentSplitter.ts
- tests/behaviour/contracts/copy_storage_to_memory/dynamic_arrays.sol
- tests/behaviour/expectations/behaviour.ts
- warplib/memory.cairo
-Handles storage/calldata assignments to memory for assignments where the lhs is an identifier (previously this case was skipped). Addresses various/destructuringAssignment.sol
-Sets location for string literal temp vars in tuple assignments to memory, addressing array/string_literal_assign_to_storage_bytes.sol
-Fixes memory suboject allocation, addressing array/create_memory_array.sol
> Data location fixes

- src/cairoUtilFuncGen/memory/arrayLiteral.ts
- src/cairoUtilFuncGen/memory/memoryRead.ts
MemoryReadGen was not picking up strings and bytes as complex types, and WM_arr was being stored purely based on initialisation length, meaning dynamic gens were being used for static and vice versa if one of the correct length had already been generated
> Fix memory read for strings/bytes

- src/passes/bytesConverter.ts
- tests/behaviour/expectations/semantic_whitelist.ts
BytesConverter runs after BuiltinHandler, meaning the `uint8(bytes24[0])` will have been replaced with just `bytes24[0]` with typestring `uint8`. This was causing the BytesConverter to skip that case since it didn't see it as a fixedbytes index access
> Fix bytes index access in type conversion

- example_contracts/nested_tuple.sol
- src/passes/tupleFixes/tupleFlattener.ts
- src/testing.ts
- tests/behaviour/contracts/expressions/tupleOfInlineArrays.sol
- tests/behaviour/expectations/behaviour.ts
Adding test for nested tuple failure, and behavior test for tuple of inline arrays.  All tests passing.
> Throwing WillNotSupportError for Nested Tuples

- src/cairoUtilFuncGen/storage/mappingIndexAccess.ts
- src/passes/generateGetters/gettersGenerator.ts
- src/passes/references/expectedLocationAnalyser.ts
- tests/behaviour/expectations/semantic_whitelist.ts
Slightly loosens the specificity when looking for reference types, catching cases which were previously being missed for mappings with strings as keys. Specifically this fixes generated getters for such instances, the last failing getter case
> String mapping getter

- src/passes/implicitConversionToExplicit.ts
- src/warplib/implementations/maths/exp.ts
- tests/behaviour/expectations/behaviour.ts
- tests/behaviour/expectations/semantic_whitelist.ts
The exp operator has special rules for type conversions. It evaluates to the type of the lhs (meaning an implicit conversion to the result type should be added to the lhs in case it's a literal) and only asserts that the rhs is unsigned, with the rhs width not effecting the operation. As such versions of the warplib function had to be implemented for all combinations of felt/Uint256 on the lhs and rhs. This was tested against all semantic exp tests and they all now pass. This was also the last failure in the cleanup tests that wasn't because of the test suite abiencoder wrapping invalid data, so they now also all pass
> Fix exp implicit type conversion

- src/passes/functionModifierHandler/functionModifierHandler.ts
- src/passes/functionModifierHandler/functionModifierInliner.ts
- src/utils/astChecking.ts
- tests/behaviour/expectations/semantic_whitelist.ts
Captures return variables going into modifiers, since they can be modified by expressions passed as arguments to the modifiers. Also comments out modifier tests that explicitly clash with other modifier tests based on whether they're testing the via-yul behaviour or the old code gen
> Modifier fixes

- src/passes/abiExtractor.ts
- tests/behaviour/contracts/abstractContracts/mappingInConstructor.sol
- tests/behaviour/expectations/behaviour.ts
Abstract contracts do not need abis generated because they cannot be deployed, and because their constructors are only called internally they can take mappings, which cannot be abi encoded.
> Do not run abiExtractor on abstract contracts

- src/passes/ifFunctionaliser.ts
- src/passes/rejectUnsupportedFeatures.ts
- src/utils/functionGeneration.ts
- src/utils/getTypeString.ts
- tests/behaviour/contracts/libraries/libStructs.sol
- tests/behaviour/expectations/behaviour.ts
Fixes libraries/using_library_structs.sol by allowing library functions to take complex inputs and fixing type lookup in the If functionaliser
> Using library structs

- src/solCompile.ts
We handle the errors from solc ourselves, if we let solc errors through our test suite thinks that transpilation failed.
> Don't print the errors from solc to stderr

- tests/behaviour/contracts/ecrecover/failing_ecrecover_invalid_input.sol
- tests/behaviour/expectations/behaviour.ts
- warplib/ecrecover.cairo
Following up #542. This implements the rest of the checks:
> Add check for invalid r/s values on ecrecover

- src/passes/expressionSplitter/expressionSplitter.ts
- tests/behaviour/contracts/conditionals/and.sol
Function kind of functionalized conditions was assigned incorrectly. E.g. it was assigning the kind as a constructor if the condition is inside a constructor.
> Fixed function kind of ternary functions

- src/passes/inheritanceInliner/functionInheritance.ts
Fixes a use of createIdentifier without a reference node that was leading to a crash with the weth10.sol contract
> Fix misuse of createIdentifier

- src/passes/sourceUnitSplitter.ts
- src/testing.ts
Uses a slightly shorter `__WC__` infix and defines a single source of truth for it.
> Cleanup contract name mangling

- package.json
- readme.md
The logo is broken on npmjs.com because it tries to resolve the image relative to the url.
While this solution is not ideal for development the logo is unlikely to change in the near
future so I see no harm in setting this absolute path.
> Use absolute path for logo

- Dockerfile
- readme.md
This pull request introduces a rudimentary Docker image to use Warp.
Users should have multiple ways to install their software. Different people use different OS. The currently provided installation methods don't suffice for common OS such as Windows. Docker images provide an elegant way to increase the accessibility of Warp. Now every OS which can run Docker can be easily used for Warp.
A fresh Dockerfile has been written. The biggest challenge was to find a suitable base image and to get all dependencies right. Among others, the `cairo-lang` package makes it non-trivial to use a lightweight image such as `alpine`. Therefore, `ubuntu:20.04` was chosen as a base image.
- Image size: 1.99GB
Build the image from inside this repository:
```bash
docker build -t warp .
```
And run the …
> Add Docker Image

- v3-core/contracts/NoDelegateCall.sol
- v3-core/contracts/UniswapV3Factory.sol
- v3-core/contracts/UniswapV3Pool.sol
- v3-core/contracts/UniswapV3PoolDeployer.sol
- v3-core/contracts/libraries/FullMath.sol
- v3-core/contracts/libraries/Oracle.sol
- v3-core/contracts/libraries/Position.sol
- v3-core/contracts/libraries/Tick.sol
- v3-core/contracts/libraries/TickBitmap.sol
- v3-core/contracts/libraries/TickMath.sol
Initially tried bumping using `solidity-upgrade` tool but it did more harm than good producing invalid code on `NoDelegateCall` and no upgrades anywhere else.
So I ended doing the bump manually, which was mostly changing implicit to explicit conversions. Also checked the code for any other breaking changes (including silent ones) according to this list [here](https://docs.soliditylang.org/en/v0.8.15/080-breaking-changes.html#how-to-update-your-code) but found none
> Uniswap bump to 0.8.14

- src/passes/returnInserter.ts
- src/passes/unreachableStatementPruner.ts
- src/utils/controlFlowAnalyser.ts
The previous CFA algorithm was causing out of memory errors. It was used in two cases, neither of which required all the information it was gathering. I've replaced it with two much smaller algorithms with vastly better space usage
> Improve efficiency of control flow algorithms

- v3-core/contracts/UniswapV3Factory.sol
- v3-core/contracts/UniswapV3Pool.sol
- v3-core/contracts/libraries/Oracle.sol
- v3-core/contracts/libraries/SqrtPriceMath.sol
- v3-core/contracts/libraries/SwapMath.sol
- v3-core/contracts/libraries/Tick.sol
- v3-core/contracts/libraries/TickBitmap.sol
- v3-core/contracts/libraries/TickMath.sol
- v3-core/contracts/test/LowGasSafeMathEchidnaTest.sol
- v3-core/contracts/test/OracleEchidnaTest.sol
- v3-core/contracts/test/SqrtPriceMathEchidnaTest.sol
- v3-core/contracts/test/TestUniswapV3Router.sol
- v3-core/contracts/test/TickBitmapEchidnaTest.sol
- v3-core/contracts/test/TickBitmapTest.sol
As conditionals are still not supported, they were transformed into if statements. In cases where there was a need to create a new variable, the conditional was changed for a function call instead in order to avoid Stack too deep compiling error
> transform conditionals

- src/index.ts
- src/starknetCli.ts
The `warp deploy` command internally uses `starknet declare` before it runs the `starknet deploy` command. This currently fails because the declare command needs the `--network` flag which does not get passed to it. Added a fix for the same. 
( To recreate the issue, run 
```
bin/warp deploy warp_output/tests/benchmark/BaseJumpRateModelV2__WC__BaseJumpRateModelV2.cairo --inputs 0,0,0,0,0 --network alpha-goerli
```
on the develop branch )
If we do not specify `--no_wallet`, the deploy command errors out with the following message:
```
Error: AssertionError: A wallet must be specified (using --wallet or the STARKNET_WALLET environment variable), unless specifically using --no_wallet.
starknet deploy failed
```
To fix this, the user can either set the `STARKNET_WALLET` env variable or pass …
> Fixes for `warp deploy` command

- src/index.ts
- src/passes/abiExtractor.ts
There was a small bug in that the inputs required the input to be a single value
which meant that the entire input had to be quoted to be passed to `--inputs`.
This updates the expectations so that the inputs are a space separated list.
We require them to be comma separated as well but this is a style choice and
can be easily changed if we wish.
The call now looks like this:
```
warp deploy --network <network> <contract> --inputs "asdf", "asdf"
```
Where as previously:
```
warp deploy --network <network> <contract> --inputs '"asdf", "asdf"'
```
Unfortunately there is a small bug in our cli library where 'array' inputs
as the one we're using for `inputs` above doesn't know when to stop parsing the
array and instead look for the next command. This means `--inputs` has
to be specified last.
> No longer require inputs to be quoted

- .github/workflows/deploy.yml
The Github workflow is failing for pushing the docusaurus site to Github Pages. 
Trying PAT instead of Github Token to see if that fixes it.
> Use PAT for pushing to Github Pages

- src/ast/ast.ts
- src/passes/expressionSplitter/conditionalFunctionaliser.ts
- src/passes/expressionSplitter/expressionSplitter.ts
- src/passes/ifFunctionaliser.ts
- src/passes/loopFunctionaliser/breakToReturn.ts
- src/passes/loopFunctionaliser/continueToLoopCall.ts
- src/passes/loopFunctionaliser/returnToBreak.ts
- src/passes/loopFunctionaliser/utils.ts
- src/passes/newToDeploy.ts
- src/passes/references/expectedLocationAnalyser.ts
- src/passes/staticArrayIndexer.ts
- src/utils/utils.ts
There were many places in the code where the closest parent which was a `FunctionDefinition` was wanted and then there was an assertion checking this parent node was not `undefined`. Also there were two methods, which enclosed this behavior, so they were the same, in different parts of the code. This PR creates a method `getContainingFunction` for these cases, that is placed in the `utils` folder of the passes.
A similar situation occurred with `SourceUnit`, so a `getContainingSourceUnit` method was created the same way.
> getContaining methods refactoring

- src/io.ts
The json files created from compiling the transpiled contracts were being deleted. Adds a fix.
> Fix --compile-cairo bug

- tests/behaviour/contracts/anonymous_parameters/func_override.sol
- tests/behaviour/expectations/behaviour.ts
No error in tests using anonymous parameters. Added tests that use uint256
> execution test for anonymous parameters

- example_contracts/using_for/complex_libraries.sol
- src/passes/referencedLibraries.ts
- src/testing.ts
The `ReferencedLibraries` pass was modified to correctly handle the case in which the referenced library refers to another and this in turn to another and so on
> Library import bug

- src/passes/warnSupportedFeatures.ts
The warning was wrongly being printed without abi.encodePacked on it. Quick fix
> Minor fix to warnings

- example_contracts/implicitsFromStub.sol
- src/passes/annotateImplicits.ts
- src/passes/cairoStubProcessor.ts
- src/testing.ts
Given a function which is used as placeholder for a Cairo stub, its implicits (and the implicits of all the functions who call's it) are determined by the stub definition and not the solidity definition.
For example:
```Solidity
pragma solidity ^0.8.14;
contract C {
///warp-cairo
///func CURRENTFUNC(){bitwise_ptr : BitwiseBuiltin* }(lhs : felt, rhs : felt) -> (res : felt):
///from starkware.cairo.common.bitwise import bitwise_or
///    let (res) = bitwise_or(lhs, rhs)
///    return (res)
///end
function f(uint8 a, uint8 b) internal pure returns (bytes32) {
return keccak256(abi.encodePacked(a, b));
}
function g() external pure {
f(10, 12);
}
}
```
In this case `g` which interacts with `f` will have `bitwise_ptr` instead of `keccak_ptr` as its implicits after transpilation
> Detect implicits from Cairo stubs

- readme.md
The current deployment instruction `warp deploy <path to Cairo contract>` returns an error when you call it. I updated it with the right deployment command.
> update deployment instruction in docs

- src/passes/inheritanceInliner/inheritanceInliner.ts
- src/passes/inheritanceInliner/libraryInheritance.ts
- tests/behaviour/contracts/libraries/libraries_in_inheritance.sol
- tests/behaviour/expectations/behaviour.ts
When the set of referenced libraries was added to the list of linearized contracts of a contract, those libraries were not being added to contracts that inherit from that contract, which should happen.
Solution:
Add a method at the beginning of the inheritanceInliner pass that handles going through the list of linearized contracts of each one of the base contracts looking for all contract ids that were not added in the current linearization list, and add them
> Bug related to libraries and inheritance

- docs/docs/features/cairo_stubs.mdx
- docs/docs/solidity_equivalents/abi_encode.mdx
Add small explanation about abi encode and erase an old warning about cairo stubs
> Minor docs update

- src/passes/rejectUnsupportedFeatures.ts
- src/transpiler.ts
- src/utils/errors.ts
- src/utils/utils.ts
- Fix bug when erroing a node source with multiple lines
- Add multiple error logging to RejectUnsupportedPass. Now after a transpilation attempt, all unsuported features are shown, instead of the first one found
> Update error logging

- src/passes/externalContractHandler/externalContractInterfaceInserter.ts
- src/passes/inheritanceInliner/constructorInheritance.ts
I can't seem to construct a minimal case which replicates this bug however it occurred as a result of transpiling https://github.com/Uniswap/v3-core/blob/main/contracts/test/TestUniswapV3Router.sol
This also fixes the issue that constructors were being added to interfaces.
> Fix member access interfaces bug

- src/ast/ast.ts
- src/passes/annotateImplicits.ts
- src/passes/expressionSplitter/conditionalFunctionaliser.ts
- src/passes/expressionSplitter/expressionSplitter.ts
- src/passes/externalContractHandler/externalContractInterfaceInserter.ts
- src/passes/functionModifierHandler/functionModifierHandler.ts
- src/passes/functionModifierHandler/functionModifierInliner.ts
- src/passes/generateGetters/gettersGenerator.ts
- src/passes/ifFunctionaliser.ts
- src/passes/loopFunctionaliser/returnToBreak.ts
- src/passes/loopFunctionaliser/utils.ts
- src/passes/newToDeploy.ts
- src/passes/staticArrayIndexer.ts
- src/passes/storageAllocator.ts
- src/passes/tupleAssignmentSplitter.ts
- src/passes/tupleFixes/tupleFiller.ts
- src/passes/variableDeclarationExpressionSplitter.ts
- src/utils/defaultValueNodes.ts
- src/utils/functionGeneration.ts
- src/utils/functionSignatureParser.ts
- src/utils/getTypeString.ts
- src/utils/nameModifiers.ts
- src/utils/nodeTemplates.ts
- src/utils/nodeTypeProcessing.ts
- src/utils/utils.ts
This PR addresses some of the audits comments related to `ModifierHandler` pass: 42, 43, 46, 47, 49, 50. They include variables renaming, code refactoring and adding comments for readability
> Audit modifiers

- src/cairoWriter.ts
- src/passes/identifierManglerPass/declarationNameMangler.ts
- src/passes/identifierManglerPass/expressionNameMangler.ts
- yarn.lock
The canonicalSignatureHash for events was being calculated in the cairoWriter, this is problematic since the bytesConverter changes all references to the `bytesN` type to its corresponding `uintM` type; so the canonicalSignatureHash would differ from the expected one if the event had a `bytesN` parameter
> Fix Event mangling

- src/index.ts
- src/io.ts
- src/utils/postCairoWrite.ts
The class_hash was computed after the compile so the compiled cairo file had the class_hash as zero
> Fix class hash zero bug

- docs/docs/getting_started/a-usage-and-installation.mdx
- example_contracts/multiple_variables.sol
- src/passes/cairoStubProcessor.ts
- src/passes/externalArgModifier/memoryRefInputModifier.ts
- src/passes/identifierManglerPass/declarationNameMangler.ts
- src/testing.ts
- src/utils/nameModifiers.ts
This pull request fix problems pointed by audit for declarationNameMangler.ts:
- Use a set for reserverdTerms to make queries faster
- Use Regex to find unsupportedCharacters in terms
- Use a unified counter to create id's for variable, internal function and new Type names
- Set a fixed width for id's in variables and internal function names to be able to sort them
Tickets:
https://www.notion.so/nethermind/AUDIT-CVF-35-declarationNameMangler-ts-de23ff0e7679484cb4f89ac58e9805aa
https://www.notion.so/nethermind/AUDIT-CVF-34-declarationNameMangler-ts-70b3c656cffc42efb6da34dce0e51701
https://www.notion.so/nethermind/AUDIT-CVF-33-declarationNameMangler-ts-1f8d615bac8a4994a0d530b97ec3e4ab
https://www.notion.so/nethermind/AUDIT-CVF-32-declarationNameMangler-ts-d69483bfcd5e4f828f1f049257354cc5
> DeclarationNameMangler_audit_fixes

- src/passes/inheritanceInliner/functionInheritance.ts
- tests/behaviour/contracts/inheritance/modifiers/inheritedModifiedFunction.sol
- tests/behaviour/expectations/behaviour.ts
Problem:
All the inherited functions get added as private functions in the current contract. Those that were externally visible need to remain externally visible here as well, so a wrapper function is created with the correct visibility and it calls the corresponding private function. This wrapper has the modifiers of the original function, since it is a clone, and the private function that is being called is also a clone, so it has the same modifiers. So all modifiers are called twice.
Solution:
Remove all modifiers from the wrapper function
> Modifiers in inherited functions

- src/passes/functionModifierHandler/functionModifierHandler.ts
- tests/behaviour/contracts/modifiers/modifierRecursive.sol
- tests/behaviour/expectations/behaviour.ts
When extracting the original function in the `ModifierHandler`, the function that is modified gets cloned, so if there is a function call inside this function to this same function (a recursive call), the referenced declaration gets rebind to the cloned function, but in this case that's not what it's needed. It should remain referencing the function that was being modified. 
In order to solve the problem, the body of the function is saved in a temporary variable, and the node's body is set to undefined. After the function is cloned, the body is attached to the cloned function.
> Modifier cloning bug

- src/cairoUtilFuncGen/abi/abiEncode.ts
- src/utils/nodeTypeProcessing.ts
- tests/behaviour/contracts/abiEncode/abiEncodePacked.sol
- tests/behaviour/expectations/behaviour.ts
- tests/behaviour/expectations/index.ts
> Update `getPackedEncoding` to return 32 bytes when dealing with addresses

- src/passes/loopFunctionaliser/index.ts
- src/passes/loopFunctionaliser/utils.ts
- src/passes/loopFunctionaliser/whileLoopToFunction.ts
This global counter was causing issues when transpiling multiple files. The counter is now zero-initialized for every AST, not every execution of the program
> Moving Global Counter for While Loops

- src/index.ts
Optimization to avoid retranspilation of files when excuting 
```bash
warp transpile <file_list>
```
Previous behaviour:
```bash
warp transpile x.sol y.sol
```
if x.sol imports y.sol, then during `x` transpilation, `y` would get transpiled as it's a dependency
Then `y` would get transpiled (again!)
Current behaviour:
`y` is transpiled only once, during the process of the transpilation of `x`
> Avoid retranspilation

- src/index.ts
- src/solCompile.ts
- src/testing.ts
- src/utils/analyseSol.ts
- tests/behaviour/expectations/semantic.ts
We remove all redundancies in compile by deferring to solc. Solc produces
a single linked ast for multiple file inputs so this resolves the full dependecy
chain.
There is a remarkable speed up to UniStark as a result of this pr.
> Remove all compile repitions for multifile input
